#!/usr/bin/env python3
"""
Rebuild image_mapping.json from existing image files.
This recovers the mapping when it gets cleared.
"""

import json
import hashlib
from pathlib import Path

IMAGES_DIR = Path(__file__).parent / "images"
MAPPING_FILE = Path(__file__).parent / "image_mapping.json"

# All books list (same as in download_images.py)
BOOKS = [
    ("Dance Dance Dance", "Haruki Murakami"),
    ("Never Let Me Go", "Kazuo Ishiguro"),
    ("Don't Lose Your Mind, Lose Your Weight", "Rujuta Diwekar"),
    ("First Lie Wins", "Ashley Elston"),
    ("The Chola Tigers: Avengers of Somnath", "Amish Tripathi"),
    ("Doctor Who: The Clockwise Man", "Justin Richards"),
    ("The Secret of Secrets (Robert Langdon, #6)", "Dan Brown"),
    ("Uncle Fred in the Springtime (Blandings Castle, #6)", "P.G. Wodehouse"),
    ("Guards! Guards! (Discworld, #8; City Watch, #1)", "Terry Pratchett"),
    ("Roadside Picnic", "Arkady Strugatsky"),
    ("The Remains of the Day", "Kazuo Ishiguro"),
    ("The Silent Patient", "Alex Michaelides"),
    ("Spiritual Awakening, Vol. 1", "Hit Premanand Govind Sharan Ji Maharaj"),
    ("White Nights", "Fyodor Dostoevsky"),
    ("Blood Like Mine", "Stuart Neville"),
    ("The Stars, Like Dust (Galactic Empire, #1)", "Isaac Asimov"),
    ("A Damsel in Distress", "P.G. Wodehouse"),
    ("The Decision Book: Fifty Models for Strategic Thinking", "Mikael Krogerus"),
    ("Full Moon (Blandings Castle, #7)", "P.G. Wodehouse"),
    ("The Almanack of Naval Ravikant", "Eric Jorgenson"),
    ("Rework", "Jason Fried"),
    ("Galahad at Blandings (Blandings Castle, #10)", "P.G. Wodehouse"),
    ("Tell-Tale Brain", "V.S. Ramachandran"),
    ("The Hidden Hindu", "Akshat Gupta"),
    ("ANDAMAN", "Ratnadip Acharya"),
    ("Sputnik Sweetheart", "Haruki Murakami"),
    ("Origin (Robert Langdon, #5)", "Dan Brown"),
    ("A Pelican at Blandings (Blandings Castle, #11)", "P.G. Wodehouse"),
    ("Elon Musk", "Walter Isaacson"),
    ("The Giver", "Lois Lowry"),
    ("The Case Of The Worried Waitress (Perry Mason, #77)", "Erle Stanley Gardner"),
    ("The Case of the Howling Dog (Perry Mason, #4)", "Erle Stanley Gardner"),
    ("The Case of the Lame Canary (Perry Mason, #11)", "Erle Stanley Gardner"),
    ("The Murder on the Links (Hercule Poirot, #2)", "Agatha Christie"),
    ("1Q84", "Haruki Murakami"),
    ("Revolutionaries", "Sanjeev Sanyal"),
    ("Child 44", "Tom Rob Smith"),
    ("The Bhagavad Gita", "Krishna-Dwaipayana Vyasa"),
    ("Very Good, Jeeves! (Jeeves, #4)", "P.G. Wodehouse"),
    ("Samanya Dharma", "Nithin Sridhar"),
    ("The Mysterious Affair at Styles (Hercule Poirot, #1)", "Agatha Christie"),
    ("One Good Deed", "David Baldacci"),
    ("Hot Water", "P.G. Wodehouse"),
    ("KARMA YOGA", "Vivekananda"),
    ("The Psychology of Money", "Morgan Housel"),
    ("Siddhartha", "Hermann Hesse"),
    ("The Myth of Sisyphus", "Albert Camus"),
    ("The Hitchhiker's Guide to the Galaxy", "Douglas Adams"),
    ("The Ocean of Churn", "Sanjeev Sanyal"),
    ("The Will to Meaning", "Viktor E. Frankl"),
    ("India in the Age of Ideas", "Sanjeev Sanyal"),
    ("Quichotte", "Salman Rushdie"),
    ("After Dark", "Haruki Murakami"),
    ("The Secret Garden", "Frances Hodgson Burnett"),
    ("Joy in the Morning (Jeeves, #8)", "P.G. Wodehouse"),
    ("The Last Lecture", "Randy Pausch"),
    ("Atomic Habits", "James Clear"),
    ("Sapiens", "Yuval Noah Harari"),
    ("Fahrenheit 451", "Ray Bradbury"),
    ("Dracula", "Bram Stoker"),
    ("The Krishna Key", "Ashwin Sanghi"),
    ("Krishna's Secret", "Devdutt Pattanaik"),
    ("Keepers of the Kalachakra", "Ashwin Sanghi"),
    ("Ikigai", "Héctor García"),
    ("Land of the Seven Rivers", "Sanjeev Sanyal"),
    ("One Hundred Years of Solitude", "Gabriel García Márquez"),
    ("The Valmiki Ramayana Vol. 3", "Vālmīki"),
    ("Why We Sleep", "Matthew Walker"),
    ("The Mahabharata: Volume 1", "Krishna-Dwaipayana Vyasa"),
    ("Man's Search for Meaning", "Viktor E. Frankl"),
    ("As a Man Thinketh", "James Allen"),
    ("Young Men in Spats", "P.G. Wodehouse"),
    ("21 Lessons for the 21st Century", "Yuval Noah Harari"),
    ("Submission", "Michel Houellebecq"),
    ("A Gentleman in Moscow", "Amor Towles"),
    ("Uncle Dynamite", "P.G. Wodehouse"),
    ("1984", "George Orwell"),
    ("Homo Deus", "Yuval Noah Harari"),
    ("The Four", "Scott Galloway"),
    ("Summer Lightning", "P.G. Wodehouse"),
    ("Five Point Someone", "Chetan Bhagat"),
    ("Something Fresh", "P.G. Wodehouse"),
    ("Wings of Fire", "A.P.J. Abdul Kalam"),
    ("Angels & Demons", "Dan Brown"),
    ("Deception Point", "Dan Brown"),
    ("Rich Dad, Poor Dad", "Robert T. Kiyosaki"),
    ("The Seventh Secret", "Irving Wallace"),
    ("Digital Fortress", "Dan Brown"),
    ("Rich Dad's Cashflow Quadrant", "Robert T. Kiyosaki"),
    ("Illusions", "Richard Bach"),
    ("The Stranger", "Albert Camus"),
    ("The Mahabharata Secret", "Christopher C. Doyle"),
    ("Jonathan Livingston Seagull", "Richard Bach"),
    ("Service With a Smile", "P.G. Wodehouse"),
    ("Rumi", "Jalal ad-Din Muhammad ar-Rumi"),
    ("Kalki Purana", "B.K. Chaturvedi"),
    ("Robots and Empire", "Isaac Asimov"),
    ("A Column of Fire", "Ken Follett"),
    ("House of Leaves", "Mark Z. Danielewski"),
    ("The Metamorphosis", "Franz Kafka"),
    ("Big Money", "P.G. Wodehouse"),
    ("The Old Man and the Sea", "Ernest Hemingway"),
    ("Dune", "Frank Herbert"),
    ("Of Counsel", "Arvind Subramanian"),
    ("The Girl in Blue", "P.G. Wodehouse"),
    ("The Master and Margarita", "Mikhail Bulgakov"),
    ("Shunya", "Sri M."),
    ("Good Omens", "Terry Pratchett"),
    ("The Palace of Illusions", "Chitra Banerjee Divakaruni"),
    ("The Peshwa", "Ram Sivasankaran"),
    ("The Street Lawyer", "John Grisham"),
    ("Nothing Lasts Forever", "Sidney Sheldon"),
    ("Freedom", "Jonathan Franzen"),
    ("Midnight's Children", "Salman Rushdie"),
    ("The Satanic Verses", "Salman Rushdie"),
    ("Sidney Sheldon's The Silent Widow", "Tilly Bagshawe"),
    ("Life over Two Beers and other stories", "Sanjeev Sanyal"),
    ("Asura: Tale Of The Vanquished", "Anand Neelakantan"),
    ("In the Shadow of the Banyan", "Vaddey Ratner"),
    ("When Breath Becomes Air", "Paul Kalanithi"),
    ("Kafka on the Shore", "Haruki Murakami"),
    ("Norwegian Wood", "Haruki Murakami"),
    ("Leave It to Psmith", "P.G. Wodehouse"),
    ("And Then There Were None", "Agatha Christie"),
    ("The Afghan", "Frederick Forsyth"),
    ("Mossad", "Michael Bar-Zohar"),
    ("Blandings Castle", "P.G. Wodehouse"),
    ("The Hidden Life of Trees", "Peter Wohlleben"),
    ("Crime and Punishment", "Fyodor Dostoevsky"),
    ("Animal Farm", "George Orwell"),
    ("The Marble Collector", "Cecelia Ahern"),
    ("By the River Piedra I Sat Down and Wept", "Paulo Coelho"),
    ("The Enchantress of Florence", "Salman Rushdie"),
    ("The Great Indian Novel", "Shashi Tharoor"),
    ("Master of the Game", "Sidney Sheldon"),
    ("Rage of Angels", "Sidney Sheldon"),
    ("The Footprints of God", "Greg Iles"),
    ("Scion of Ikshvaku", "Amish Tripathi"),
    ("The Great Gatsby", "F. Scott Fitzgerald"),
    ("Playing It My Way", "Sachin Tendulkar"),
    ("Shalimar the Clown", "Salman Rushdie"),
    ("The Lovely Bones", "Alice Sebold"),
    ("The Sicilian", "Mario Puzo"),
    ("Beatrice and Virgil", "Yann Martel"),
    ("The Sceptical Patriot", "Sidin Vadukut"),
    ("Harry Potter and the Half-Blood Prince", "J.K. Rowling"),
    ("Plaster City", "Johnny Shaw"),
    ("This Book Does Not Exist", "Mike Schneider"),
    ("I Am the Messenger", "Markus Zusak"),
    ("A Painted House", "John Grisham"),
    ("Keep off the Grass", "Karan Bajaj"),
    ("The Oath of the Vayuputras", "Amish Tripathi"),
    ("The Lowland", "Jhumpa Lahiri"),
    ("Right Ho, Jeeves & Carry On, Jeeves", "P.G. Wodehouse"),
    ("The Da Vinci Code", "Dan Brown"),
    ("Pride and Prejudice", "Jane Austen"),
    ("The Book Thief", "Markus Zusak"),
    ("The Other Side of Midnight", "Sidney Sheldon"),
    ("The Immortals of Meluha", "Amish Tripathi"),
    ("Wicked Lovely", "Melissa Marr"),
    ("A Brief History of Time", "Stephen W. Hawking"),
    ("Evil Under the Sun", "Agatha Christie"),
    ("Inferno", "Dan Brown"),
    ("The Catcher in the Rye", "J.D. Salinger"),
    ("So Long, and Thanks for All the Fish", "Douglas Adams"),
    ("Ink Exchange", "Melissa Marr"),
    ("Harry Potter and the Chamber of Secrets", "J.K. Rowling"),
    ("A Thousand Splendid Suns", "Khaled Hosseini"),
    ("The Witch of Portobello", "Paulo Coelho"),
    ("The Lost Symbol", "Dan Brown"),
    ("8th Confession", "James Patterson"),
    ("Fooled by Randomness", "Nassim Nicholas Taleb"),
    ("Maximum City", "Suketu Mehta"),
    ("The Family", "Mario Puzo"),
    ("The Godfather", "Mario Puzo"),
    ("Jeeves and the Feudal Spirit", "P.G. Wodehouse"),
    ("Joy: The Happiness That Comes from Within", "Osho"),
    ("Harry Potter and the Deathly Hallows", "J.K. Rowling"),
    ("If Tomorrow Comes", "Sidney Sheldon"),
    ("The Namesake", "Jhumpa Lahiri"),
    ("Into the Silent Land", "Paul Broks"),
    ("One Night at the Call Center", "Chetan Bhagat"),
    ("Omerta (The Godfather)", "Mario Puzo"),
    ("Catch-22", "Joseph Heller"),
    ("Anything for You, Ma'am", "Raheja Tushar"),
    ("Harry Potter and the Prisoner of Azkaban", "J.K. Rowling"),
    ("The Fountainhead", "Ayn Rand"),
    ("False Impression", "Jeffrey Archer"),
    ("The Celestial Bed", "Irving Wallace"),
    ("The Last Don", "Mario Puzo"),
    ("Life, the Universe and Everything", "Douglas Adams"),
    ("Twilight", "Stephenie Meyer"),
    ("The 3 Mistakes of My Life", "Chetan Bhagat"),
    ("The Kite Runner", "Khaled Hosseini"),
    ("Harry Potter and the Sorcerer's Stone", "J.K. Rowling"),
    ("The Case of the One-Eyed Witness", "Erle Stanley Gardner"),
    ("The Secret Adversary", "Agatha Christie"),
    ("2 States", "Chetan Bhagat"),
    ("I, Robot", "Isaac Asimov"),
    ("Right Ho, Jeeves", "P.G. Wodehouse"),
    ("Airport", "Arthur Hailey"),
    ("The Case of the Lonely Heiress", "Erle Stanley Gardner"),
    ("Black Holes and Baby Universes", "Stephen W. Hawking"),
    ("Harry Potter and the Goblet of Fire", "J.K. Rowling"),
    ("The Count of Monte Cristo", "Alexandre Dumas"),
    ("Oh Life! Relax Please", "Sukhabodhanandha"),
    ("The Miracle", "Irving Wallace"),
    ("The Search", "John Battelle"),
    ("A Briefer History of Time", "Stephen W. Hawking"),
    ("The Time Machine", "H.G. Wells"),
    ("The Inscrutable Americans", "Anurag Mathur"),
    ("The Second Lady", "Irving Wallace"),
    ("To Kill a Mockingbird", "Harper Lee"),
    ("The First P. G. Wodehouse Omnibus", "P.G. Wodehouse"),
    ("The Firm", "Robin Waterfield"),
    ("Veronika Decides to Die", "Paulo Coelho"),
    ("The Silence of the Lambs", "Thomas Harris"),
    ("Hotel", "Arthur Hailey"),
    ("The Secret of the Nagas", "Amish Tripathi"),
    ("The Universe in a Nutshell", "Stephen W. Hawking"),
    ("Tell Me Your Dreams", "Sidney Sheldon"),
    ("Surely You're Joking, Mr. Feynman!", "Richard P. Feynman"),
    ("The Case of the Amorous Aunt", "Erle Stanley Gardner"),
    ("The Alchemist", "Paulo Coelho"),
    ("Not a Penny More, Not a Penny Less", "Jeffrey Archer"),
    ("The Graveyard Book", "Neil Gaiman"),
    ("The Almighty", "Irving Wallace"),
    ("The Case of the Caretaker's Cat", "Erle Stanley Gardner"),
    ("The Fan Club", "Irving Wallace"),
    ("Harry Potter and the Order of the Phoenix", "J.K. Rowling"),
    ("Fragile Eternity (Wicked Lovely, #3)", "Melissa Marr"),
    ("The Restaurant at the End of the Universe", "Douglas Adams"),
    ("Operation Karakoram", "Arvind Nayar"),
    ("Mostly Harmless", "Douglas Adams"),
    ("The Ultimate Hitchhiker's Guide to the Galaxy", "Douglas Adams"),
]

def get_image_hash(title, author):
    """Get hash for filename."""
    key = f"{title}|{author}".lower()
    return hashlib.md5(key.encode()).hexdigest()[:10]

def rebuild_mapping():
    """Rebuild mapping from existing image files."""
    print("Rebuilding image_mapping.json from existing files...\n")
    
    # Get all existing image files
    image_files = set(f.stem for f in IMAGES_DIR.glob("*.jpg"))
    
    print(f"Found {len(image_files)} image files\n")
    
    # Build mapping by computing hashes for all books
    mapping = {}
    found = 0
    
    for title, author in BOOKS:
        hash_name = get_image_hash(title, author)
        if hash_name in image_files:
            mapping[f"{title}|{author}"] = f"{hash_name}.jpg"
            found += 1
    
    # Save rebuilt mapping
    with open(MAPPING_FILE, 'w') as f:
        json.dump(mapping, f, indent=2)
    
    print(f"Rebuilt mapping with {found} entries")
    print(f"Mapping saved to {MAPPING_FILE}\n")
    
    return mapping

if __name__ == "__main__":
    mapping = rebuild_mapping()
